project:
  type: book
  output-dir: docs

prefer-html: true

language:
  section-title-appendices: "Lampiran"
  section-title-references: "Referensi"
  toc-title-document: "Daftar isi"
  title-block-affiliation-single: "Afiliasi"
  title-block-affiliation-plural: "Afiliasi"
  crossref-fig-title: "Gambar"
  crossref-tbl-title: "Tabel"
  crossref-eq-prefix: "Persamaan"
  

book:
  title: "Pemodelan Statistika pada Data Geospasial"
  subtitle: "Studi Kasus dan Ilustrasi dengan R"
  author: 
    - name: Prof. Dr. Ir. Anik Djuraidah, MS.
      email: anikdjuraidah@apps.ipb.ac.id
      affiliations:
      - name: Departemen Statistika IPB University
        city: Bogor
        country: Indonesia
  repo-url: https://github.com/statistika-spasial/book
  site-url: https://statistika-spasial.github.io/book
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: part-1.qmd
      chapters: 
        - 01-SpasialAutoRegresifModel.qmd 
        - 02-SpasialDurbinModel.qmd
        - 03-SpasialAutoRegresifBinomialNegatif.qmd 
    
    - part: part-2.qmd
      chapters: 
        - 04-RegresiTerbobotiGeografis.qmd 
        - 05-RegresiTerbobotiGeografisCampuran.qmd
        - 06-RegresiTerbobotiGeografisBinomialNegatif.qmd
    
    - part: part-3.qmd
      chapters: 
        - 07-Data.qmd 
        - 08-MetodeAnalisis.qmd
        - 09-TahapanR.qmd    
    
    - part: part-4.qmd
      chapters: 
        - 10-ModelDependensiSpasial.qmd 
        - 11-ModelKeragamanSpasial.qmd
    
    - ModelEpidemiologi.qmd
  
  appendices: 
    - references.qmd

bibliography: 
  - packages.bib
  - book.bib
  - references.bib

knitr:
  opts_chunk: 
    collapse: true
    comment: "#" 
    R.options:
      knitr.graphics.auto_pdf: true
      dplyr.print_min: 6
      dplyr.print_max: 6
      stars.crs: 17
      digits: 3

format:
  html:
    number-depth: 3
    theme: cosmo
    code-fold: false
    code-summary: "Code"
    code-tools: true
    code-link: true
    knitr:
      opts_chunk:
        out.width: 100%
        R.options:
          width: 68

