# 1. Model Dependensi Spasial {#sec-model-dependensi-spasial-intro .unnumbered}

Dependensi spasial merupakan suatu hubungan korelasi antara variabel dengan dirinya sendiri atau suatu ukuran dari kemiripan objek di dalam suatu ruang (jarak, waktu dan wilayah). Adanya kemiripan nilai dari lokasi-lokasi yang berdekatan dan cenderung berkelompok akan ditunjukkan dengan dependensi spasial positif. Sedangkan jika lokasi-lokasi yang berdekatan mempunyai nilai yang berbeda dan cenderung menyebar maka akan ditunjukkan dengan dependensi spasial yang negatif [@kosfeld2006].

Untuk mengetahui adanya dependensi spasial dilakukan melalui uji statistik Moran’s I dan uji Pengganda Lagrange (Lagrange Multiplier, LM). Hipotesis nol pada kedua pengujian ini adalah dalam model tidak ada efek spasial. Jika `p-value` uji tersebut lebih kecil dari taraf signifikansi yang ditetapkan maka dapat dikatakan bahwa dalam model terdapat efek spasial. 

Pemodelan pada regresi spasial dilakukan dengan menambahkan matriks spasial atau *contiguity* ($W$) pada model regresi yang digunakan. Penambahan matriks $W$ tersebut dapat dilakukan pada variabel-variabel dependen (parameter koefisien regresinya akan disimbolkan dengan $\rho$), pada variabel independen (parameter koefisien regresinya akan disimbolkan dengan γ), maupun pada error term (parameter koefisien akan regresinya disimbolkan dengan $\lambda$) atau kombinasi dari dua maupun ketiga efeknya. 

Jika efeknya hanya nyata terhadap parameter $\rho$ maka model disebut model **Spatial Autoregressive Regression (SAR)**. Jika efeknya hanya nyata terhadap parameter γ maka model disebut model **Spatial Lag-X (SLX)**. Jika efeknya hanya nyata terhadap parameter $\lambda$ maka model disebut **Spatial Error Model (SEM)**. Jika efeknya hanya nyata terhadap parameter $\rho$ dan $\lambda$ maka model disebut **General Spatial Model (GSM)**. Jika efeknya hanya nyata terhadap parameter $\rho$ dan γ maka model disebut **Spatial Durbin Model (SDM)**. Jika efeknya hanya nyata terhadap parameter $\lambda$ dan γ maka model disebut **Spatial Durbin Error Model (SDEM)**. Jika efeknya nyata terhadap ketiga parameter ($\rho$, $\lambda$ dan γ) maka model disebut **General Spasial Nested (GNS)**.
