# 2. Model Keragaman Spasial {#sec-model-keragaman-spasial-intro .unnumbered}

Keragaman spasial dapat terjadi karena adanya perbedaan karakteristik antara satu titik pengamatan dengan titik pengamatan lainnya. Untuk mengetahuinya dilakukan pengujian Breusch-Pagan dengan hipotesis nol adalah antar lokasi memiliki keragaman/varians yang sama. Jika `p-value` uji ini lebih kecil dari taraf signifikansi yang ditetapkan maka dapat ditarik kesimpulan bahwa terdapat keragaman spasial atau varian antar lokasi yang berbeda. Sehingga alternatif model spasial yang digunakan adalah model **Geographically Weighted Regression (GWR)**.

Namun dalam model GWR, koefisien regresi masing-masing lokasi memiliki nilai yang berbeda-beda sehingga dianggap masih kurang tepat sehingga dikembangkan **Mixed Geographically Weighted Regression (MGWR)**. Pada MGWR dihasilkan estimator atau penduga parameter yang sebagian bersifat global dan sebagian yang lain bersifat lokal sesuai dengan lokasi pengamatan [@purhadi2012].